### ISSUE TITLE
Split functions into lib

### ISSUE THREAD

**Issue by k4ml** [r0lodex/jomwebot#2]
This will make testing easier. Currently it's not possible to `require('./server')` for testing as `bot.on()` will block forever. With this splitting, only `bot.on()` remain in `server.js`. Others should be moved to `./lib/`.

**Comment by k4ml** [comment]
Or we can use this method - http://stackoverflow.com/questions/4981891/node-js-equivalent-of-pythons-if-name-main

``` js
if (require.main === module) {
    console.log('XXXXXXX');
    bot.on('message', function(data) {
        console.log(data)
        if (data.new_chat_participant) {
            bot.sendMessage({
                chat_id: data.chat.id,
                text: 'Selamat datang ' + data.new_chat_participant.first_name + '!\nKalau boleh, panas-panaskan badan dengan sedikit intro. Kerja kat mana, dan bidang kepakaran. Yang lain nanti kitorang tanya2 la ye. \n\nKalau nak kenal orang2 dalam ni, klik /ahli atau taip /siapa [nama ahli].'
            })
        } else if (data.text.charAt(0) === '/') {
            var a = data.text.split(' ');
            try {
                botcommands[a[0].slice(1)](data, a);
            } catch(error) {
                // Command is not supported
            }
        }
    });
}
```

But it turned out that instantiating the bot already run in unfinite loop. So `bot = new _bot({})` also need to be in above block.

**Comment by r0lodex** [comment]
Agreed.

**Comment by r0lodex** [comment]
As per this [commit](https://github.com/r0lodex/jomwebot/commit/aaf9403af9ac21a55f66690e84dca815495173fd#diff-fabcaa97871555b68aa095335975e613) `server.js` is now the composition. `botcommands` and the rest of the distortion is now modular. I will consider this issue closed.

Thanks for the heads up!
